update public.bottlings set name_kr = $w$- 아남 나 할바$w$ where name = $w$- Anam na h-Alba$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(1982) - 몰츠 오브 스코틀랜드$w$ where name = $w$(1982) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(1991/2016) - 고든 앤 컴퍼니$w$ where name = $w$(1991/2016) - Gordon & Company$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(1994/2019) - 잔지바$w$ where name = $w$(1994/2019) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2006) dreamy nighttime drink 캐스크 108.34 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$(2006) A dreamy nighttime drink Cask 108.34 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2006/2024) - 몰츠 오브 스코틀랜드$w$ where name = $w$(2006/2024) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2008/2019) Scottish Roadsign 에디션 No. 11 - 플리켄쉴트$w$ where name = $w$(2008/2019) Scottish Roadsign Edition No. 11 - Flickenschild$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2008/2020) - 잔지바$w$ where name = $w$(2008/2020) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2008/2021) - 시그나토리 빈티지$w$ where name = $w$(2008/2021) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2009) Grown-Up Indulgences 캐스크 55.72 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$(2009) Grown-Up Indulgences Cask 55.72 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2009/2011) - 시그나토리 빈티지$w$ where name = $w$(2009/2011) - Singatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2009/2021) - 고든 앤 맥페일$w$ where name = $w$(2009/2021) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2010) Dream 오브 Scotland - 브륄러 위스키하우스$w$ where name = $w$(2010) A Dream Of Scotland - Brühler Whiskyhaus$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2010/2023) - 잔지바$w$ where name = $w$(2010/2023) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2011/2023) - 몰츠 오브 스코틀랜드$w$ where name = $w$(2011/2023) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2012/2022) - 몰츠 오브 스코틀랜드$w$ where name = $w$(2012/2022) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2012/2022) #308764 - 시그나토리 빈티지$w$ where name = $w$(2012/2022) #308764 - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2012/2024) Trinity Vintage 시리즈$w$ where name = $w$(2012/2024) The Trinity Vintage Series$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2013/2024) - 몰츠 오브 스코틀랜드$w$ where name = $w$(2013/2024) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2013/2024) - 몰츠 오브 스코틀랜드$w$ where name = $w$(2013/2024) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2013/2024) Margaux 캐스크 London Showcase - 베리 브라더스 앤 러드$w$ where name = $w$(2013/2024) Margaux Cask London Showcase - Berry Bros. & Rudd$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2015/2023) - 잔지바$w$ where name = $w$(2015/2023) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2015/2023) - 잔지바$w$ where name = $w$(2015/2023) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2016/2023) - 잔지바$w$ where name = $w$(2016/2023) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2017/2020) ManOSword 파운더스 셀렉션 캐스크 348$w$ where name = $w$(2017/2020) ManOSword Founders Selection Cask 348$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2017/2024) STR 캐스크 - 베스트 드램$w$ where name = $w$(2017/2024) STR Cask - Best Dram$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2018/2022) 엑스-레드 와인 & 엑스 버번 인 엑스-모스카텔 피니시 - 게누스라우姆 파더보른$w$ where name = $w$(2018/2022) Ex-Red Wine & Ex-Bourbon in Ex-Moscatel Finish - Genussraum Paderborn$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2018/2022) 올로로소 셰리 캐스크$w$ where name = $w$(2018/2022) Oloroso Sherry Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2020/2024) 바베이도스 럼 캐스크$w$ where name = $w$(2020/2024) Rum Barbados Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(2024) 루비 포트 피니시$w$ where name = $w$(2024) Ruby Port Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(40%)$w$ where name = $w$(40%)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$(45%)$w$ where name = $w$(45%)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년$w$ where name = $w$10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 - 82 챕터 to Newcastle$w$ where name = $w$10 Years - 82 Chapters to Newcastle$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2007/2017) - .D. 래트레이$w$ where name = $w$10 Years (2007/2017) - A.D. Rattray$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2007/2019) - 더글라스 랭$w$ where name = $w$10 Years (2007/2019) - Douglas Laing$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2011/2021) - 반 위스$w$ where name = $w$10 Years (2011/2021) - van Wees$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2012/2023) - 시그나토리 빈티지$w$ where name = $w$10 Years (2012/2023) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2013) Mingle into darkness 캐스크 78.84 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$10 Years (2013) Mingle into darkness Cask 78.84 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2013/2024) - 더글라스 랭$w$ where name = $w$10 Years (2013/2024) - Douglas Laing$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2013/2024) - 드람 모어$w$ where name = $w$10 Years (2013/2024) - Dràm Mòr$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2014/2024) - 제임스 이디$w$ where name = $w$10 Years (2014/2024) - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2014/2024) - 제임스 이디$w$ where name = $w$10 Years (2014/2024) - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2014/2024) - 톰슨 브라더스$w$ where name = $w$10 Years (2014/2024) - Thompson Bros$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 (2023 릴리즈)$w$ where name = $w$10 Years (2023 Release)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 블루프린트 버번 배럴$w$ where name = $w$10 Years Blueprint Bourbon Barrel$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 블루프린트 크림 셰리$w$ where name = $w$10 Years Blueprint Cream Sherry$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 블루프린트 토스티드 배럴$w$ where name = $w$10 Years Blueprint Toasted Barrel$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 캐스크 스트렝스 (2026)$w$ where name = $w$10 Years Cask Strength (2026)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 CS 배치 8 (2022)$w$ where name = $w$10 Years CS Batch 8 (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$10년 unpeated$w$ where name = $w$10 Years unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$101$w$ where name = $w$101$w$ and name_kr is null;
update public.bottlings set name_kr = $w$101$w$ where name = $w$101$w$ and name_kr is null;
update public.bottlings set name_kr = $w$105 캐스크 스트렝스$w$ where name = $w$105 Cask Strength$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2009/2021) - 캐스크 116 - 브레이브 뉴 스피리츠$w$ where name = $w$11 Years (2009/2021) - Cask 116 - Brave New Spirits$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2009/2021) - 올드 프렌즈$w$ where name = $w$11 Years (2009/2021) - The Old Friends$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2009/2021) - 반 위스$w$ where name = $w$11 Years (2009/2021) - van Wees$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2010/2022) Contrasts 피트 스모크$w$ where name = $w$11 Years (2010/2022) Contrasts Peat Smoke$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2012/2023) - 베스트 드램$w$ where name = $w$11 Years (2012/2023) - Best Dram$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2012/2024) - 시그나토리 빈티지$w$ where name = $w$11 Years (2012/2024) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2013/2025) - 제임스 이디$w$ where name = $w$11 Years (2013/2025) - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2014/2025) - 제임스 이디$w$ where name = $w$11 Years (2014/2025) - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2018) - 고든 앤 맥페일$w$ where name = $w$11 Years (2018) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 (2024) Offerman 4th 에디션$w$ where name = $w$11 Years (2024) Offerman 4th Edition$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 Ambrosial Feast - 디아지오 스페셜 릴리즈 (2024)$w$ where name = $w$11 Years Ambrosial Feast - Diageo Special Releases (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 Malaga 캐스크 피니시 - 제임스 이디$w$ where name = $w$11 Years Malaga Cask Finish - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$11년 Offerman 에디션$w$ where name = $w$11 Years Offerman Edition$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 더블 캐스크$w$ where name = $w$12 Year Old Double Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 바이킹 아너$w$ where name = $w$12 Year Old Viking Honour$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년$w$ where name = $w$12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 - 82 챕터 to Newcastle$w$ where name = $w$12 Years - 82 Chapters to Newcastle$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2008/2021) old - 럼 숙성 & 코냑 피니시$w$ where name = $w$12 Years (2008/2021) old - Rum Matured & Cognac Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2009/2021) - 몰츠 오브 스코틀랜드$w$ where name = $w$12 Years (2009/2021) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2009/2022) - 시그나토리 빈티지$w$ where name = $w$12 Years (2009/2022) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2010/2023) - 잔지바$w$ where name = $w$12 Years (2010/2023) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2011) Spiced vanilla chai cake 캐스크 105.45 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$12 Years (2011) Spiced vanilla chai cake Cask 105.45 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2012/2024) - 캐스크 하운드$w$ where name = $w$12 Years (2012/2024) - The Cask Hound$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2012/2024) Contrasts High Enzyme$w$ where name = $w$12 Years (2012/2024) Contrasts High Enzyme$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2012/2024) Frühburgunder 바리크 피니시$w$ where name = $w$12 Years (2012/2024) Frühburgunder Barrique Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2012/2025) - 시그나토리 빈티지$w$ where name = $w$12 Years (2012/2025) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2017)$w$ where name = $w$12 Years (2017)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2024)$w$ where name = $w$12 Years (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2024) Fireside Tales - 디아지오 스페셜 릴리즈 (2024)$w$ where name = $w$12 Years (2024) Fireside Tales - Diageo Special Releases (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 (2025)$w$ where name = $w$12 Years (2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 더블 캐스크$w$ where name = $w$12 Years Double Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 더블 오크$w$ where name = $w$12 Years Double Oak$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 더블우드$w$ where name = $w$12 Years Doublewood$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 올로로소 피니시 - Darkness!$w$ where name = $w$12 Years Oloroso Finish - Darkness!$w$ and name_kr is null;
update public.bottlings set name_kr = $w$12년 Origami Kite 2 - 디아지오 스페셜 릴리즈 (2024)$w$ where name = $w$12 Years Origami Kite 2 - Diageo Special Releases (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$13년 - 82 챕터 to Newcastle$w$ where name = $w$13 Years - 82 Chapters to Newcastle$w$ and name_kr is null;
update public.bottlings set name_kr = $w$13년 (2008/2023) - 시그나토리 빈티지$w$ where name = $w$13 Years (2008/2023) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$13년 (2024) Tasteful 8 - 브륄러 위스키하우스$w$ where name = $w$13 Years (2024) The Tasteful 8 - Brühler Whiskyhaus$w$ and name_kr is null;
update public.bottlings set name_kr = $w$13년 퍼스트필 아메리칸 오크$w$ where name = $w$13 Years 1st Fill American Oak$w$ and name_kr is null;
update public.bottlings set name_kr = $w$13년 Bas-아르마냑 캐스크 피니시$w$ where name = $w$13 Years Bas-Armagnac Cask Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년$w$ where name = $w$14 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년$w$ where name = $w$14 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년$w$ where name = $w$14 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년$w$ where name = $w$14 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년 - 82 챕터 to Newcastle$w$ where name = $w$14 Years - 82 Chapters to Newcastle$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년 (2007/2021) - 몰츠 오브 스코틀랜드$w$ where name = $w$14 Years (2007/2021) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년 (2009) 컬렉션 오브 Curious 캐스크$w$ where name = $w$14 Years (2009) A Collection of Curious Casks$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년 (2010/2024) - 코발 버번 배럴$w$ where name = $w$14 Years (2010/2024) - Koval Bourbon Barrel$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년 (2024) Icons 오브 Campbeltown - 릴리즈 No. 2: 드래곤$w$ where name = $w$14 Years (2024) Icons of Campbeltown - Release No. 2: The Dragon$w$ and name_kr is null;
update public.bottlings set name_kr = $w$14년 Called to Submission - 브레이브 뉴 스피리츠$w$ where name = $w$14 Years Called to Submission - Brave New Spirits$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 솔레라$w$ where name = $w$15 Year Old Solera$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년$w$ where name = $w$15 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년$w$ where name = $w$15 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년$w$ where name = $w$15 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년$w$ where name = $w$15 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 (2003) 모스번 No. 24$w$ where name = $w$15 Years (2003) Mossburn No. 24$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 (2006/2021)$w$ where name = $w$15 Years (2006/2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 (2006/2022)$w$ where name = $w$15 Years (2006/2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 (2007/2023) Mouton bouillie 캐스크 66.239 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$15 Years (2007/2023) Mouton bouillie Cask 66.239 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 (2008/2023) - 몰츠 오브 스코틀랜드$w$ where name = $w$15 Years (2008/2023) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 (2008/2024)$w$ where name = $w$15 Years (2008/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 마데이라 캐스크$w$ where name = $w$15 Years Madeira Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$15년 바이킹 하트$w$ where name = $w$15 Years Viking Heart$w$ and name_kr is null;
update public.bottlings set name_kr = $w$16년$w$ where name = $w$16 Year Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$16년$w$ where name = $w$16 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$16년$w$ where name = $w$16 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$16년$w$ where name = $w$16 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$17년 (2005) Infrequent Flyers - Alistair Walker 위스키 Company$w$ where name = $w$17 Years (2005) Infrequent Flyers - Alistair Walker Whisky Company$w$ and name_kr is null;
update public.bottlings set name_kr = $w$17년 (2006/2024)$w$ where name = $w$17 Years (2006/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년 셰리 오크$w$ where name = $w$18 Year Old Sherry Oak$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년$w$ where name = $w$18 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년$w$ where name = $w$18 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년$w$ where name = $w$18 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년$w$ where name = $w$18 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년$w$ where name = $w$18 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년 (2006/2024) - 시그나토리 빈티지$w$ where name = $w$18 Years (2006/2024) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$18년 (2021) French 레드 와인 캐스크$w$ where name = $w$18 Years (2021) French Red Wine Casks$w$ and name_kr is null;
update public.bottlings set name_kr = $w$19년 (1996/2015) - 시그나토리 빈티지$w$ where name = $w$19 Years (1996/2015) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$19년 (1997/2016) - 시그나토리 빈티지$w$ where name = $w$19 Years (1997/2016) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$19년 (1998/2017) - 몰츠 오브 스코틀랜드$w$ where name = $w$19 Years (1998/2017) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$20년 - Observatory$w$ where name = $w$20 Years - The Observatory$w$ and name_kr is null;
update public.bottlings set name_kr = $w$20년 (2003/2023) Speymalt - 고든 앤 맥페일$w$ where name = $w$20 Years (2003/2023) Speymalt - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$20년 (2004/2024) Speymalt - 고든 앤 맥페일$w$ where name = $w$20 Years (2004/2024) Speymalt - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년$w$ where name = $w$21 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년$w$ where name = $w$21 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년$w$ where name = $w$21 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년 - Rising 리저브 No. 3 - 루비 포트 캐스크$w$ where name = $w$21 Years - Rising Reserve No. 3 - Ruby Port Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년 - Rising 리저브 No. 4 - 화이트 와인 캐스크$w$ where name = $w$21 Years - Rising Reserve No. 4 - White Wine Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년 (2003/2024) - 우 드램 클랜$w$ where name = $w$21 Years (2003/2024) - Wu DRAM Clan$w$ and name_kr is null;
update public.bottlings set name_kr = $w$21년 Grand Crescendo - 디아지오 스페셜 릴리즈 (2024)$w$ where name = $w$21 Years Grand Crescendo - Diageo Special Releases (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$225$w$ where name = $w$225$w$ and name_kr is null;
update public.bottlings set name_kr = $w$228$w$ where name = $w$228$w$ and name_kr is null;
update public.bottlings set name_kr = $w$23년 (2023) Rude Olph - 바메 몰츠$w$ where name = $w$23 Years (2023) Rude Olph - VAME Malts$w$ and name_kr is null;
update public.bottlings set name_kr = $w$24년 (1953) - 고든 앤 맥페일$w$ where name = $w$24 Years (1953) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$24년 (1992/2016) - 몰츠 오브 스코틀랜드$w$ where name = $w$24 Years (1992/2016) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$24년 (1996/2020) - 잔지바$w$ where name = $w$24 Years (1996/2020) - Sansibar$w$ and name_kr is null;
update public.bottlings set name_kr = $w$24년 (1997) - 랄프 스테드먼 X 캐스크 88$w$ where name = $w$24 Years (1997) - Ralph Steadman X Cask 88$w$ and name_kr is null;
update public.bottlings set name_kr = $w$25년 (2023) 125주년 애니버서리$w$ where name = $w$25 Year Old (2023) 125th Anniversary$w$ and name_kr is null;
update public.bottlings set name_kr = $w$25년$w$ where name = $w$25 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$25년 (2023) - 고든 앤 맥페일$w$ where name = $w$25 Years (2023) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$25년 (2023) - 고든 앤 맥페일$w$ where name = $w$25 Years (2023) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$25년 마데이라 피니시$w$ where name = $w$25 Years Madeira Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$26년 (1988/2014) - 하트 브라더스$w$ where name = $w$26 Years (1988/2014) - Hart Brothers$w$ and name_kr is null;
update public.bottlings set name_kr = $w$26년 (1991/2018) - 베리 브라더스 앤 러드$w$ where name = $w$26 Years (1991/2018) - Berry Bros. & Rudd$w$ and name_kr is null;
update public.bottlings set name_kr = $w$27년 (2024) Tasteful 8 - 브륄러 위스키하우스$w$ where name = $w$27 Years (2024) The Tasteful 8 - Brühler Whiskyhaus$w$ and name_kr is null;
update public.bottlings set name_kr = $w$29년 (1987/2017) - 케이든헤드$w$ where name = $w$29 Years (1987/2017) - Cadenhead's$w$ and name_kr is null;
update public.bottlings set name_kr = $w$3년 (2020/2023) PX 캐스크$w$ where name = $w$3 Years (2020/2023) PX Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$30년 (1987/2018) Xtra Particular - 더글라스 랭$w$ where name = $w$30 Years (1987/2018) Xtra Old Particular - Douglas Laing$w$ and name_kr is null;
update public.bottlings set name_kr = $w$30년 (1993/2023) - 몰츠 오브 스코틀랜드$w$ where name = $w$30 Years (1993/2023) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$30년 (1994/2024) - 데카던트 드링크스$w$ where name = $w$30 Years (1994/2024) - Decadent Drinks$w$ and name_kr is null;
update public.bottlings set name_kr = $w$31년 (1987/2019) - 위미스 몰츠$w$ where name = $w$31 Years (1987/2019) - Wemyss Malts$w$ and name_kr is null;
update public.bottlings set name_kr = $w$31년 (1991) - 혹스헤드 임포츠$w$ where name = $w$31 Years (1991) - Hogshead Imports$w$ and name_kr is null;
update public.bottlings set name_kr = $w$31년 (1991) - 랄프 스테드먼 X 캐스크 88$w$ where name = $w$31 Years (1991) - Ralph Steadman X Cask 88$w$ and name_kr is null;
update public.bottlings set name_kr = $w$33년 (1989) Espresso romano 캐스크 70.48 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$33 Years (1989) Espresso romano Cask 70.48 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$34년 (1984/2019) - 반 위스$w$ where name = $w$34 Years (1984/2019) - van Wees$w$ and name_kr is null;
update public.bottlings set name_kr = $w$35년 (1987/2023) - 머레이 맥데이비드$w$ where name = $w$35 Years (1987/2023) - Murray McDavid$w$ and name_kr is null;
update public.bottlings set name_kr = $w$40년 (1975/2015) - 몰츠 오브 스코틀랜드$w$ where name = $w$40 Years (1975/2015) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$40년 (1983/2023) - 몰츠 오브 스코틀랜드$w$ where name = $w$40 Years (1983/2023) - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$40년 배치 2 (2022)$w$ where name = $w$40 Years Batch 2 (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$4th 릴리즈 16년 (2023)$w$ where name = $w$4th Release 16 Years (2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$5년 - Wajos$w$ where name = $w$5 Years - Wajos$w$ and name_kr is null;
update public.bottlings set name_kr = $w$5년 (2018/2023)$w$ where name = $w$5 Years (2018/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$500$w$ where name = $w$500$w$ and name_kr is null;
update public.bottlings set name_kr = $w$7년 (2017/2025) Bohemian Schnapsidee - 바메 몰츠$w$ where name = $w$7 Years (2017/2025) Bohemian Schnapsidee - VAME Malts$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년$w$ where name = $w$8 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년 (2013/2022) - 캐스크 Wizard$w$ where name = $w$8 Years (2013/2022) - The Cask Wizard$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년 (2013/2022) 바리크 피니시 - 베스트 드램$w$ where name = $w$8 Years (2013/2022) Barrique Finish - Best Dram$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년 (2015/2023) - 시그나토리 빈티지$w$ where name = $w$8 Years (2015/2023) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년 (2016/2024)$w$ where name = $w$8 Years (2016/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년$w$ where name = $w$8 Years Old$w$ and name_kr is null;
update public.bottlings set name_kr = $w$8년 Tidal Churn - 디아지오 스페셜 릴리즈 (2024)$w$ where name = $w$8 Years Tidal Churn - Diageo Special Releases (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 (2011/2020) - 헌터 랭$w$ where name = $w$9 Years (2011/2020) - Hunter Laing$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 (2014/2023) - 시그나토리 빈티지$w$ where name = $w$9 Years (2014/2023) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 (2014/2024) Contrasts unpeated$w$ where name = $w$9 Years (2014/2024) Contrasts unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 (2015/2024) - 제임스 이디$w$ where name = $w$9 Years (2015/2024) - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 아몬티야도 셰리 캐스크 피니시 - 우드 컬렉션$w$ where name = $w$9 Years Amontillado Sherry Cask Finish - The Wood Collection$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 피노 셰리 캐스크 피니시 - 우드 컬렉션$w$ where name = $w$9 Years Fino Sherry Cask Finish - The Wood Collection$w$ and name_kr is null;
update public.bottlings set name_kr = $w$9년 올로로소 셰리 캐스크 피니시 - 우드 컬렉션$w$ where name = $w$9 Years Oloroso Sherry Cask Finish - The Wood Collection$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아부나흐$w$ where name = $w$A'bunadh$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아바솔로 멕시칸 콘 위스키$w$ where name = $w$Abasolo Mexican Corn Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Abbey MCDXCIV$w$ where name = $w$Abbey MCDXCIV$w$ and name_kr is null;
update public.bottlings set name_kr = $w$AD 04.22:02$w$ where name = $w$AD 04.22:02$w$ and name_kr is null;
update public.bottlings set name_kr = $w$AD 10.21:06$w$ where name = $w$AD 10.21:06$w$ and name_kr is null;
update public.bottlings set name_kr = $w$AD:02.22 피티드 캐스크 스트렝스$w$ where name = $w$AD:02.22 Peated Cask Strength$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아지테이터 Chestnut 캐스크$w$ where name = $w$Agitator Chestnut Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$알트 글렌 레거시 시리즈$w$ where name = $w$Allt Gleann The Legacy Series$w$ and name_kr is null;
update public.bottlings set name_kr = $w$안 오아$w$ where name = $w$An Oa$w$ and name_kr is null;
update public.bottlings set name_kr = $w$안녹 12년$w$ where name = $w$anCnoc 12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$안녹 18년 (2024)$w$ where name = $w$anCnoc 18 Years (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아온 Amarone (2020/2025)$w$ where name = $w$Aon Amarone (2020/2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아온 칼바도스 (2017/2025)$w$ where name = $w$Aon Calvados (2017/2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아온 화이트 포트 (2020/2025)$w$ where name = $w$Aon White Port (2020/2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$에이펙스 Pomegranate 배치 8$w$ where name = $w$APEX Pomegranate Batch 8$w$ and name_kr is null;
update public.bottlings set name_kr = $w$에이펙스 화이트 와인$w$ where name = $w$APEX White Wine$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아포지 XII 12년$w$ where name = $w$Apogee XII 12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아드코어 커미티 릴리즈$w$ where name = $w$Ardcore Committee Release$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아란 10년$w$ where name = $w$Arran 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아란 24년 (1996) - 랄프 스테드먼 X 캐스크 88$w$ where name = $w$Arran 24 Years (1996) - Ralph Steadman X Cask 88$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아란 25년 (2020)$w$ where name = $w$Arran 25 Years (2020)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아이러즈 레드 오가닉 싱글몰트 (2019/2024)$w$ where name = $w$Ayrer's Red Organic Single Malt (2019/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베이비 블루$w$ where name = $w$Baby Blue$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베이커스 7 (2015/2023)$w$ where name = $w$Baker's 7 (2015/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$발코미$w$ where name = $w$Balcomie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$발레친 19년 (2004/2023)$w$ where name = $w$Ballechin 19 Years (2004/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$발리 Distillery 에디션 Makers Mark 버번 캐스크$w$ where name = $w$Barley Distillery Edition Makers Mark Bourbon Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$배치 R02$w$ where name = $w$Batch R02$w$ and name_kr is null;
update public.bottlings set name_kr = $w$배치 스트렝스 (2024)$w$ where name = $w$Batch Strength (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$보샹 위스키 Pur 몰트$w$ where name = $w$Beauchamp Whisky Pur Malt$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베게만 위스키 Eichenschild 5년$w$ where name = $w$Begemann Whisky Eichenschild 5 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Best Drinking Friends 릴리즈 No. 3 (2018/2024)$w$ where name = $w$Best Drinking Friends Release No. 3 (2018/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베츠 자메이카 럼 캐스크 (2017/2022) 배치 1$w$ where name = $w$Betz Jamaica Rum Cask (2017/2022) Batch 1$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베츠 Master 블렌드 배치 4$w$ where name = $w$Betz Master Blend Batch 4$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베츠 PX 싱글 캐스크 (2017/2021) 52$w$ where name = $w$Betz PX Single Cask (2017/2021) 52$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베츠 라이 싱글 캐스크 (2017/2022) 50$w$ where name = $w$Betz Rye Single Cask (2017/2022) 50$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베츠 소테른 캐스크 (2017/2022) 배치 1$w$ where name = $w$Betz Sauternes Cask (2017/2022) Batch 1$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베버바흐 위트 몰트 Einbecker 저먼 비어 캐스크 피니시$w$ where name = $w$Beverbach Wheat Malt Einbecker German Beer Cask Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$블랙 부시$w$ where name = $w$Black Bush$w$ and name_kr is null;
update public.bottlings set name_kr = $w$블랙 포레스트 8년 (2014/2022) - vom Fass$w$ where name = $w$Black Forest 8 Years (2014/2022) - vom Fass$w$ and name_kr is null;
update public.bottlings set name_kr = $w$본디드$w$ where name = $w$Bonded$w$ and name_kr is null;
update public.bottlings set name_kr = $w$부커스 스몰 배치 (2019) 01E$w$ where name = $w$Bookers Small Batch (2019) 01E$w$ and name_kr is null;
update public.bottlings set name_kr = $w$버번 Ratafia 샹프누아 캐스크 T-053$w$ where name = $w$Bourbon Ratafia Champenois Cask T-053$w$ and name_kr is null;
update public.bottlings set name_kr = $w$브레이즈 블렌디드$w$ where name = $w$Breizh Blended$w$ and name_kr is null;
update public.bottlings set name_kr = $w$브리간티아 10년 (2014/2024) 샤르도네 싱글 캐스크 증류소 한정판$w$ where name = $w$Brigantia 10 Years (2014/2024) Chardonnay Single Cask Distillery Exclusive$w$ and name_kr is null;
update public.bottlings set name_kr = $w$브리간티아 5년 (2018/2023) 코냑 싱글 캐스크$w$ where name = $w$Brigantia 5 Years (2018/2023) Cognac Single Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$브림스톤$w$ where name = $w$Brimstone$w$ and name_kr is null;
update public.bottlings set name_kr = $w$브로디르 Final 배치$w$ where name = $w$Brodir Final Batch$w$ and name_kr is null;
update public.bottlings set name_kr = $w$버드 스펜서 - 레전드 - 라우히히 - 배치 02$w$ where name = $w$Bud Spencer - The Legend - Rauchig - Batch 02$w$ and name_kr is null;
update public.bottlings set name_kr = $w$버드 스펜서 - 레전드 - 라우히히 - 배치 03$w$ where name = $w$Bud Spencer - The Legend - Rauchig - Batch 03$w$ and name_kr is null;
update public.bottlings set name_kr = $w$버팔로 트레이스$w$ where name = $w$Buffalo Trace$w$ and name_kr is null;
update public.bottlings set name_kr = $w$불릿 95 라이$w$ where name = $w$Bulleit 95 Rye$w$ and name_kr is null;
update public.bottlings set name_kr = $w$불릿 버번 10년$w$ where name = $w$Bulleit Bourbon 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$카디어스 (2024) 캐스크 페이버릿츠 10년$w$ where name = $w$Cairdeas (2024) Cask Favourites 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$캠벨타운 로크 에디션 (2023)$w$ where name = $w$Campbeltown Loch Edition (2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$캐스크 스트렝스 배치 1$w$ where name = $w$Cask Strength Batch 1$w$ and name_kr is null;
update public.bottlings set name_kr = $w$캐스크 스트렝스 배치 12$w$ where name = $w$Cask Strength Batch 12$w$ and name_kr is null;
update public.bottlings set name_kr = $w$셀트$w$ where name = $w$Celt$w$ and name_kr is null;
update public.bottlings set name_kr = $w$클래식 라디$w$ where name = $w$Classic Laddie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$클래식 싱글몰트$w$ where name = $w$Classic Single Malt$w$ and name_kr is null;
update public.bottlings set name_kr = $w$코피 그레인 위스키$w$ where name = $w$Coffey Grain Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$코피 몰트 위스키$w$ where name = $w$Coffey Malt Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$코냑 캐스크 8년 (2017/2025)$w$ where name = $w$Cognac Cask 8 Years (2017/2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Core 배치 R0.01$w$ where name = $w$Core Batch R0.01$w$ and name_kr is null;
update public.bottlings set name_kr = $w$코리브레칸$w$ where name = $w$Corryvreckan$w$ and name_kr is null;
update public.bottlings set name_kr = $w$디스틸러스 초이스 특별 에디션 2 (2025)$w$ where name = $w$Distiller's Choice Sonderedition 2 (2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$디스틸러스 리저브$w$ where name = $w$Distiller's Reserve$w$ and name_kr is null;
update public.bottlings set name_kr = $w$디스틸러스 셀렉트$w$ where name = $w$Distiller's Select$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Distillers Choice 바리크 R$w$ where name = $w$Distillers Choice Barrique R$w$ and name_kr is null;
update public.bottlings set name_kr = $w$디스틸러리 셀렉트 No.1$w$ where name = $w$Distillery Select No.1$w$ and name_kr is null;
update public.bottlings set name_kr = $w$더블 캐스크$w$ where name = $w$Double Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$더블 Trouble - 피티드$w$ where name = $w$Double Trouble – Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$더블우드 12$w$ where name = $w$DoubleWood 12$w$ and name_kr is null;
update public.bottlings set name_kr = $w$이글 레어 10년$w$ where name = $w$Eagle Rare 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Eiskeller-위스키 12년 싱글 캐스크 Fass 4$w$ where name = $w$Eiskeller-Whisky 12 Years Single Cask Fass 4$w$ and name_kr is null;
update public.bottlings set name_kr = $w$엘스번 Rivesaltes 캐스크 - 배치 No. 001$w$ where name = $w$Elsburn Rivesaltes Casks - Batch No. 001$w$ and name_kr is null;
update public.bottlings set name_kr = $w$엘스번 저니 (2020)$w$ where name = $w$Elsburn The Journey (2020)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$엘스번 저니 (2021)$w$ where name = $w$Elsburn The Journey (2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$에밀 Kraftwerk$w$ where name = $w$Emill Kraftwerk$w$ and name_kr is null;
update public.bottlings set name_kr = $w$에버만 Theo 블렌디드 위스키$w$ where name = $w$Evermann Theo Blended Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$에버만 Wilhelm 싱글몰트 위스키$w$ where name = $w$Evermann Wilhelm Single Malt Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$엑스 셰리 올로로소 싱글 캐스크 - 울트라 헤빌리 피티드 (2017/2024)$w$ where name = $w$ex Sherry Oloroso Single Cask – Ultra Heavily Peated (2017/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$엑스 토카이 아수 싱글 캐스크 (2019/2026)$w$ where name = $w$ex Tokaji Aszú Single Cask (2019/2026)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$익셉셔널 레인지 엑스 무기 소주 - 마일드$w$ where name = $w$Exceptional Range ex Mugi Shochu – Mild$w$ and name_kr is null;
update public.bottlings set name_kr = $w$익셉셔널 레인지 미즈나라 - 피티드$w$ where name = $w$Exceptional Range Mizunara – Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$익셉셔널 레인지 미즈나라 (2025) - 소프트 피티드$w$ where name = $w$Exceptional Range Mizunara (2025) – Soft Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$팔켄 5년 (2022)$w$ where name = $w$Falken 5 Years (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$팔로우 에디션 (퍼스트 크롭)$w$ where name = $w$Fallow Edition (First Crop)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$핑글라시 8년 (2017/2025) - 제임스 이디$w$ where name = $w$Finglassie 8 Years (2017/2025) - James Eadie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$파이어드 오크 10년$w$ where name = $w$Fired Oak 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$퓨전$w$ where name = $w$Fusion$w$ and name_kr is null;
update public.bottlings set name_kr = $w$길로스 (2014) 셰리 Duett$w$ where name = $w$Gilors (2014) Sherry Duett$w$ and name_kr is null;
update public.bottlings set name_kr = $w$길로스 10년 PX 셰리$w$ where name = $w$Gilors 10 Years PX Sherry$w$ and name_kr is null;
update public.bottlings set name_kr = $w$고르프 위스키 캐스크 1$w$ where name = $w$GORFH Whiskey Cask 1$w$ and name_kr is null;
update public.bottlings set name_kr = $w$고르프 위스키 Oat (2025)$w$ where name = $w$GORFH Whiskey Oat (2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$그레이브 디거 Erdfassreifung 엑스휴메이션 - 챕터 II - 피티드$w$ where name = $w$Grave Digger Erdfassreifung Exhumation – Chapter II – Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$그린 스팟$w$ where name = $w$Green Spot$w$ and name_kr is null;
update public.bottlings set name_kr = $w$핸드 필드 증류소 한정판 11년 배치 1$w$ where name = $w$Hand Filled Distillery Exclusive 11 Years Batch 1$w$ and name_kr is null;
update public.bottlings set name_kr = $w$핸드필드 (2025) 엑스 Dry Gin Heimat Distillers$w$ where name = $w$Handfilled (2025) ex Dry Gin Heimat Distillers$w$ and name_kr is null;
update public.bottlings set name_kr = $w$핸드필드 라이 & Jack Daniels$w$ where name = $w$Handfilled Rye & Jack Daniels$w$ and name_kr is null;
update public.bottlings set name_kr = $w$핸드필드 위스키 - 엑스 샴페인 Vin Clair - 언피티드$w$ where name = $w$Handfilled Whisky – ex Champagner Vin Clair – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$하란 12년 셰리 캐스크 피니시$w$ where name = $w$Haran 12 Years Sherry Cask Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$하베스트 에디션 (퍼스트 크롭)$w$ where name = $w$Harvest Edition (First Crop)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$헤이즐번 15년 (2006/2022)$w$ where name = $w$Hazelburn 15 Years (2006/2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Heather Distillery 에디션 (2017/2021)$w$ where name = $w$Heather Distillery Edition (2017/2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Heavy 메탈 에디션 Birmingham - 홈 오브 메탈 - 언피티드$w$ where name = $w$Heavy Metal Edition Birmingham – Home of Metal – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$헤단 (2021/2025)$w$ where name = $w$Hedan (2021/2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$하이 웨스트 더블 라이 위스키$w$ where name = $w$High West Double Rye Whiskey$w$ and name_kr is null;
update public.bottlings set name_kr = $w$헌트리스 레몬 메도우 (2019/2025)$w$ where name = $w$Huntress Lemon Meadow (2019/2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$헌트리스 몰티드 티케이크 (2017/2026)$w$ where name = $w$Huntress Malted Teacake (2017/2026)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$헌트리스 오처드 코블러 (2019/2024)$w$ where name = $w$Huntress Orchard Cobbler (2019/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$I Am 루트, 투! - 스피리츠 알케미스트$w$ where name = $w$I Am Root, Too! - The Spirits Alchemist$w$ and name_kr is null;
update public.bottlings set name_kr = $w$인텔리겐스 AI:01$w$ where name = $w$Intelligens AI:01$w$ and name_kr is null;
update public.bottlings set name_kr = $w$인텔리겐스 AI:02$w$ where name = $w$Intelligens AI:02$w$ and name_kr is null;
update public.bottlings set name_kr = $w$IPA Experiment (2022)$w$ where name = $w$IPA Experiment (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아일라 (LA) 34년 (1990/2025) - 시그나토리 빈티지 x Wu Dram Clan$w$ where name = $w$Islay (LA) 34 Years (1990/2025) - Signatory Vintage x Wu Dram Clan$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아일라 블렌디드 몰트 스카치 위스키 Kildalton 19년 (2024) - 리빙 소울즈$w$ where name = $w$Islay Blended Malt Scotch Whisky Kildalton 19 Years (2024) - Living Souls$w$ and name_kr is null;
update public.bottlings set name_kr = $w$제임슨 블랙 배럴$w$ where name = $w$Jameson Black Barrel$w$ and name_kr is null;
update public.bottlings set name_kr = $w$제임슨 캐스크메이츠 IPA 에디션 (2017)$w$ where name = $w$Jameson Caskmates IPA Edition (2017)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$제임슨 캐스크메이츠 스타우트 에디션 (2020)$w$ where name = $w$Jameson Caskmates Stout Edition (2020)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$주다스 프리스트 터보 - 언피티드 (2024)$w$ where name = $w$Judas Priest Turbo – Unpeated (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$주라 10년$w$ where name = $w$Jura 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Kentucky Derby 148$w$ where name = $w$Kentucky Derby 148$w$ and name_kr is null;
update public.bottlings set name_kr = $w$킬케란 12년$w$ where name = $w$Kilkerran 12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$킬케란 8년 (2024) 배치 10$w$ where name = $w$Kilkerran 8 Years (2024) Batch 10$w$ and name_kr is null;
update public.bottlings set name_kr = $w$키나한스 아이리시 위스키 KASC 프로젝트 배치 03$w$ where name = $w$Kinahan's Irish Whiskey KASC Project Batch 03$w$ and name_kr is null;
update public.bottlings set name_kr = $w$킹카 40th 애니버서리 에디션 (2012/2020)$w$ where name = $w$King Car 40th Anniversary Edition (2012/2020)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$랑스킵$w$ where name = $w$Langskip$w$ and name_kr is null;
update public.bottlings set name_kr = $w$라산타 12 셰리 캐스크$w$ where name = $w$Lasanta 12 Sherry Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레칙 16년 (2005/2022) - 시그나토리 빈티지$w$ where name = $w$Ledaig 16 Years (2005/2022) - Signatory Vintage$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레칙 17년 (2006/2024) - 고든 앤 맥페일$w$ where name = $w$Ledaig 17 Years (2006/2024) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레칙 17년 (2006/2024) - 고든 앤 맥페일$w$ where name = $w$Ledaig 17 Years (2006/2024) - Gordon & MacPhail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레칙 앤 토버모리 18년 (2024) - 리빙 소울즈$w$ where name = $w$Ledaig and Tobermory 18 Years (2024) - Living Souls$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레프트 필드$w$ where name = $w$Left-Field$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레거시$w$ where name = $w$Legacy$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레전드$w$ where name = $w$Legend$w$ and name_kr is null;
update public.bottlings set name_kr = $w$롱로우 피티드 (2021)$w$ where name = $w$Longrow Peated (2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$롯 No. 40 라이 위스키$w$ where name = $w$Lot No. 40 Rye Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$러브 포션$w$ where name = $w$Love Potion$w$ and name_kr is null;
update public.bottlings set name_kr = $w$마데이라 피니시$w$ where name = $w$Madeira Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$메이커스 마크$w$ where name = $w$Maker's Mark$w$ and name_kr is null;
update public.bottlings set name_kr = $w$미클 토어 5년 Chinquapin One (2023)$w$ where name = $w$Meikle Tòir 5 Years The Chinquapin One (2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Midnight Dusk - 디아지오 스페셜 릴리즈 (2024)$w$ where name = $w$Midnight Dusk - Diageo Special Releases (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$마일드 & 프루티 (2022)$w$ where name = $w$Mild & Fruity (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Myth$w$ where name = $w$Myth$w$ and name_kr is null;
update public.bottlings set name_kr = $w$나두라 (2015)$w$ where name = $w$Nadurra (2015)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$닉니아 오가닉 배치 5 (2017/2021)$w$ where name = $w$Nc'nea Organic Batch 5 (2017/2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$닛카 데이즈$w$ where name = $w$Nikka Days$w$ and name_kr is null;
update public.bottlings set name_kr = $w$닛카 더 그레인 위스키$w$ where name = $w$Nikka The Grain Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$나인 스프링스 10년 PX 피니시$w$ where name = $w$Nine Springs 10 Years PX Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$옥타브 배럴스 Octavius 3년 (2018/2021)$w$ where name = $w$Octave Barrels The Octavius 3 Years (2018/2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$옥토모어 10.3 6년 (2013/2019)$w$ where name = $w$Octomore 10.3 6 Years (2013/2019)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$옥토모어 13년 (2024) Tasteful 8 - 브륄러 위스키하우스$w$ where name = $w$Octomore 13 Years (2024) The Tasteful 8 - Brühler Whiskyhaus$w$ and name_kr is null;
update public.bottlings set name_kr = $w$올드 포레스터 86 프루프$w$ where name = $w$Old Forester 86 Proof$w$ and name_kr is null;
update public.bottlings set name_kr = $w$올드 풀트니 12년 (2023)$w$ where name = $w$Old Pulteney 12 Years (2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$올드 풀트니 18년$w$ where name = $w$Old Pulteney 18 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$올로로소 셀렉트 캐스크$w$ where name = $w$Oloroso Select Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$오가닉 (2019/2024) 캐스크 스트렝스 배치 GD06$w$ where name = $w$Organic (2019/2024) Cask Strength Batch GD06$w$ and name_kr is null;
update public.bottlings set name_kr = $w$오가닉 배치 20 (2019/2023)$w$ where name = $w$Organic Batch 20 (2019/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$아워 발리$w$ where name = $w$Our Barley$w$ and name_kr is null;
update public.bottlings set name_kr = $w$P&M 레드 오크$w$ where name = $w$P&M Red Oak$w$ and name_kr is null;
update public.bottlings set name_kr = $w$파트리스브루나 마데이라 캐스크 (2018)$w$ where name = $w$Patrisbrunna Madeira Cask (2018)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$파트리스브루나 오리지널 Paderborner 싱글몰트 (2016)$w$ where name = $w$Patrisbrunna Original Paderborner Single Malt (2016)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$파트리스브루나 피티드 (2017)$w$ where name = $w$Patrisbrunna Peated (2017)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$파트리스브루나 X-Mas 포트 (2016) 더블 캐스크$w$ where name = $w$Patrisbrunna X-Mas Port (2016) Double Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 캐스크 피니시$w$ where name = $w$Port Cask Finish$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 샬롯 10$w$ where name = $w$Port Charlotte 10$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 샬롯 14년 (2023) - 브륄러 위스키하우스$w$ where name = $w$Port Charlotte 14 Years (2023) - Brühler Whiskyhaus$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 샬롯 18년 (2004/2023)$w$ where name = $w$Port Charlotte 18 Years (2004/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 피니시 - 머레이 맥데이비드$w$ where name = $w$Port Finish - Murray McDavid$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 루이그$w$ where name = $w$Port Ruighe$w$ and name_kr is null;
update public.bottlings set name_kr = $w$포트 우드 피니시 12년$w$ where name = $w$Port Wood Finish 12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$팟 스틸 버번$w$ where name = $w$Pot Still Bourbon$w$ and name_kr is null;
update public.bottlings set name_kr = $w$쿼터 캐스크$w$ where name = $w$Quarter Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$콰이어트 레벨스 Gordon (2009/2023)$w$ where name = $w$Quiet Rebels Gordon (2009/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레어 브리드$w$ where name = $w$Rare Breed$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Rebels 0,0 몰트 블렌드$w$ where name = $w$Rebels 0,0 Malt Blend$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레드브레스트 12년$w$ where name = $w$Redbreast 12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레드브레스트 12년 캐스크 스트렝스 (2022)$w$ where name = $w$Redbreast 12 Years Cask Strength (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레드브레스트 15년$w$ where name = $w$Redbreast 15 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레드브레스트 21년$w$ where name = $w$Redbreast 21 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레드브레스트 토니 포트$w$ where name = $w$Redbreast Tawny Port$w$ and name_kr is null;
update public.bottlings set name_kr = $w$레세르바 안달루시아$w$ where name = $w$Reserva Andalucia$w$ and name_kr is null;
update public.bottlings set name_kr = $w$리저브 캐스크$w$ where name = $w$Reserve Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$리치 & 스모키 (2022)$w$ where name = $w$Rich & Smoky (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$리치하게 숙성 15년 - (2005)$w$ where name = $w$Richly Matured 15 Years - (2005)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$리슬링 와인 캐스크 Grand Cru 에디션 (2021)$w$ where name = $w$Riesling Wine Cask Grand Cru Edition (2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$로제 와인 캐스크 (2022)$w$ where name = $w$Rose Wine Cask (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$로슬락스위스키 EKO 셰리 올로로소 2x30 (2015)-(2022)$w$ where name = $w$Roslagswhisky EKO Sherry Oloroso 2x30 (2015)-(2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$루아드 모어 (2011/2024) Jack the Ripper - 몰츠 오브 스코틀랜드$w$ where name = $w$Ruadh Maor (2011/2024) Jack the Ripper - Malts of Scotland$w$ and name_kr is null;
update public.bottlings set name_kr = $w$루아드 모어 12년 - 드람 모어$w$ where name = $w$Ruadh Maor 12 Years - Dràm Mòr$w$ and name_kr is null;
update public.bottlings set name_kr = $w$슐리처 싱글몰트 클래식$w$ where name = $w$Schlitzer Single Malt Klassisch$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스코치 커미티 릴리즈$w$ where name = $w$Scorch Committee Release$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스콜피온스 - 록 빌리버 (2025)$w$ where name = $w$Scorpions - Rock Believer (2025)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스콜피온스 - 60년 오브 록$w$ where name = $w$Scorpions – 60 Years of Rock$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스콜피온스 Crazy 월드 - 언피티드$w$ where name = $w$Scorpions Crazy World – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$셀렉트 캐스크$w$ where name = $w$Select Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Sie nannten ihn Spencer - 언피티드$w$ where name = $w$Sie nannten ihn Spencer – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Fifteen$w$ where name = $w$Signature Edition Fifteen$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Four$w$ where name = $w$Signature Edition Four$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Fourteen - 언피티드$w$ where name = $w$Signature Edition Fourteen – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Nine$w$ where name = $w$Signature Edition Nine$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Seventeen$w$ where name = $w$Signature Edition Seventeen$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Sixteen$w$ where name = $w$Signature Edition Sixteen$w$ and name_kr is null;
update public.bottlings set name_kr = $w$시그니처 에디션 Thirteen$w$ where name = $w$Signature Edition Thirteen$w$ and name_kr is null;
update public.bottlings set name_kr = $w$질트 Flören (2018/2023) 싱글 캐스크 5년$w$ where name = $w$Sild Flören (2018/2023) Single Cask 5 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 배럴$w$ where name = $w$Single Barrel$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 배럴 셀렉트$w$ where name = $w$Single Barrel Select$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 캐스크 - David’s Choice - 언피티드$w$ where name = $w$Single Cask – David’s Choice – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 캐스크 - 아이리시 Style - 언피티드$w$ where name = $w$Single Cask – Irish Style – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 캐스크 - Turf Tail Distillers Cut - 피티드$w$ where name = $w$Single Cask – Turf Tail Distillers Cut – Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 캐스크 - 울트라 헤빌리 피티드$w$ where name = $w$Single Cask – Ultra Heavily Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 캐스크 Nr. 2 (2024)$w$ where name = $w$Single Cask Nr. 2 (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글몰트 (NAS)$w$ where name = $w$Single Malt (NAS)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글몰트 아이리시 위스키 (2021)$w$ where name = $w$Single Malt Irish Whiskey (2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글몰트 미야기쿄$w$ where name = $w$Single Malt Miyagikyo$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글몰트 미야기쿄 아로마틱 이스트 에디션 (2022)$w$ where name = $w$Single Malt Miyagikyo Aromatic Yeast Edition (2022)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글몰트 요이치$w$ where name = $w$Single Malt Yoichi$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글 팟 스틸 (2024)$w$ where name = $w$Single Pot Still (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스카이$w$ where name = $w$Skye$w$ and name_kr is null;
update public.bottlings set name_kr = $w$슬립낫 No.9 위스키$w$ where name = $w$Slipknot No.9 Whiskey$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스몰 배치$w$ where name = $w$Small Batch$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스몰 배치$w$ where name = $w$Small Batch$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스모크 Distillery 에디션 칼바도스 캐스크$w$ where name = $w$Smoke Distillery Edition Calvados Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스모크헤드 15년 (2025) - 이안 맥클라우드$w$ where name = $w$Smokehead 15 Years (2025) - Ian Mcleod$w$ and name_kr is null;
update public.bottlings set name_kr = $w$솔레 4년 (2017)$w$ where name = $w$Sole 4 Years (2017)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$솔리스트 브랜디 캐스크 (2014/2021)$w$ where name = $w$Solist Brandy Cask (2014/2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$솔리스트 엑스 버번 캐스크 B141231048A$w$ where name = $w$Solist Ex Bourbon Cask B141231048A$w$ and name_kr is null;
update public.bottlings set name_kr = $w$SOLIST 피노 셰리 캐스크$w$ where name = $w$SOLIST Fino Sherry Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$솔리스트 셰리 캐스크$w$ where name = $w$Solist Sherry Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Sonderabfüllung 엑스 Apricot 브랜디$w$ where name = $w$Sonderabfüllung ex Apricot Brandy$w$ and name_kr is null;
update public.bottlings set name_kr = $w$소버린$w$ where name = $w$Sovereign$w$ and name_kr is null;
update public.bottlings set name_kr = $w$소잉 에디션 (세컨드 크롭)$w$ where name = $w$Sowing Edition (Second Crop)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Steinkeller-위스키 12년 싱글 캐스크 Fass 8$w$ where name = $w$Steinkeller-Whisky 12 Years Single Cask Fass 8$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스튜라더$w$ where name = $w$Stiuireadair$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스톰$w$ where name = $w$Storm$w$ and name_kr is null;
update public.bottlings set name_kr = $w$스트레이트 라이 위스키$w$ where name = $w$Straight Rye Whiskey$w$ and name_kr is null;
update public.bottlings set name_kr = $w$산토리 히비키 하모니$w$ where name = $w$Suntory Hibiki Harmony$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Surge$w$ where name = $w$Surge$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Tag des Deutschen Whiskys (2023)$w$ where name = $w$Tag des Deutschen Whiskys (2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$타케츠루 퓨어 몰트$w$ where name = $w$Taketsuru Pure Malt$w$ and name_kr is null;
update public.bottlings set name_kr = $w$테겔베르크 라프로익 캐스크$w$ where name = $w$Tegelberg Laphroaig Cask$w$ and name_kr is null;
update public.bottlings set name_kr = $w$테렌스 힐 - 히어로 - 위스키 (mild)$w$ where name = $w$Terence Hill – The Hero – Whisky (mild)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Texas 라이$w$ where name = $w$Texas Rye$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Texas 싱글몰트$w$ where name = $w$Texas Single Malt$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Arcadian 오가닉 가이아 1.2$w$ where name = $w$The Arcadian Organic Gaia 1.2$w$ and name_kr is null;
update public.bottlings set name_kr = $w$블랙 Grouse 알파 에디션$w$ where name = $w$The Black Grouse Alpha Edition$w$ and name_kr is null;
update public.bottlings set name_kr = $w$클래식 라디$w$ where name = $w$The Classic Laddie$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Early 데이즈 - Ketterer Wash X St. Kilian - 언피티드$w$ where name = $w$The Early Days – Ketterer Wash X St. Kilian – Unpeated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$English 9년 (2013) Slicing 앤 dicing 캐스크 137.18 - 스카치 몰트 위스키 소사이어티$w$ where name = $w$The English 9 Years (2013) Slicing and dicing Cask 137.18 - The Scotch Malt Whisky Society$w$ and name_kr is null;
update public.bottlings set name_kr = $w$English 위스키 인피니티 캐스크 - 증류소 한정판 (2024) 배치 3$w$ where name = $w$The English Whisky Infinity Cask - Distillery Exclusive (2024) Batch 3$w$ and name_kr is null;
update public.bottlings set name_kr = $w$풀 아이리시 (2024)$w$ where name = $w$The Full Irish (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Hielan 8년$w$ where name = $w$The Hielan 8 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Liberator 포트 'n' Peat - 스토어하우스 스페셜 배치 18$w$ where name = $w$The Liberator Port 'n' Peat – Storehouse Special Batch 18$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Macleans 영 테디 (2023)$w$ where name = $w$The Macleans Young Teddy (2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$오리지널 10$w$ where name = $w$The Original 10$w$ and name_kr is null;
update public.bottlings set name_kr = $w$피티드 2022$w$ where name = $w$The Peated 2022$w$ and name_kr is null;
update public.bottlings set name_kr = $w$퀸타 루반 14년$w$ where name = $w$The Quinta Ruban 14 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$싱글톤 오브 더프타운 12년$w$ where name = $w$The Singleton Of Dufftown 12 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW121$w$ where name = $w$The Westfalian TW121$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW129$w$ where name = $w$The Westfalian TW129$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW134$w$ where name = $w$The Westfalian TW134$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW181$w$ where name = $w$The Westfalian TW181$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW256$w$ where name = $w$The Westfalian TW256$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW34$w$ where name = $w$The Westfalian TW34$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW40$w$ where name = $w$The Westfalian TW40$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW57$w$ where name = $w$The Westfalian TW57$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW73$w$ where name = $w$The Westfalian TW73$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW74$w$ where name = $w$The Westfalian TW74$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW8$w$ where name = $w$The Westfalian TW8$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Westfalian TW86$w$ where name = $w$The Westfalian TW86$w$ and name_kr is null;
update public.bottlings set name_kr = $w$타이거 에디션$w$ where name = $w$Tiger Edition$w$ and name_kr is null;
update public.bottlings set name_kr = $w$트리플 셰리 캐스크 (2021)$w$ where name = $w$Triple Sherry Cask (2021)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$트리플 우드 (2024)$w$ where name = $w$Triple Wood (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$우가달$w$ where name = $w$Uigeadail$w$ and name_kr is null;
update public.bottlings set name_kr = $w$UUAHOUUA WIESky 7년 - 피노 누아$w$ where name = $w$UUAHOUUA WIESky 7 Years - Pinot Noir$w$ and name_kr is null;
update public.bottlings set name_kr = $w$발러$w$ where name = $w$Valour$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Vibrant Stills 버번 배럴 8년 (2015/2023)$w$ where name = $w$Vibrant Stills Bourbon Barrel 8 Years (2015/2023)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$Vibrant Stills 소테른 캐스크 8년 (2016/2024)$w$ where name = $w$Vibrant Stills Sauternes Cask 8 Years (2016/2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$빈크 피티드 포트 5년$w$ where name = $w$Vink Peated Port 5 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$웨어하우스 2 배치 003$w$ where name = $w$Warehouse 2 Batch 003$w$ and name_kr is null;
update public.bottlings set name_kr = $w$위 비스티 5년$w$ where name = $w$Wee Beastie 5 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$베스트하이머 Bier-위스키$w$ where name = $w$Westheimer Bier-Whisky$w$ and name_kr is null;
update public.bottlings set name_kr = $w$웨스키 - 헤시안 콘 위스키 - 10년$w$ where name = $w$Whesskey - Hessian Corn Whisky - 10 Years$w$ and name_kr is null;
update public.bottlings set name_kr = $w$위스키 원더스 오브 우드 시리즈 3 스웨디시 오크$w$ where name = $w$Whiskey Wonders of Wood Series 3 Swedish Oak$w$ and name_kr is null;
update public.bottlings set name_kr = $w$위스키 벙커 리저브 (2025) - 피티드$w$ where name = $w$Whisky Bunker Reserve (2025) - Peated$w$ and name_kr is null;
update public.bottlings set name_kr = $w$위스키 프롬 더 배럴$w$ where name = $w$Whisky From The Barrel$w$ and name_kr is null;
update public.bottlings set name_kr = $w$위스키 솔레라 - 피티드 - III (2024)$w$ where name = $w$Whisky Solera – Peated – III (2024)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$윌로우번 증류소 한정판 캐스크 (1445)$w$ where name = $w$WillowBurn The Distillery Exclusive Cask (1445)$w$ and name_kr is null;
update public.bottlings set name_kr = $w$x 팔리 - 와일더 시즈 - XO 코냑 캐스크 피니시 (2023)$w$ where name = $w$x Parley - Wilder Seas - XO Cognac Cask Finish (2023)$w$ and name_kr is null;
